### ISSUE TITLE
Convert to mp4 format

### ISSUE THREAD

**Issue by perrin4869** [psirenny/gulp-fluent-ffmpeg#1]
Trying to convert an mp3 file to mp4, I got the following error: `ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument`

After doing some digging, it turns out that you cannot convert to using pipes. That means that while the following works:

```
ffmpeg -i client/audio/foo.mp3  -c:a libfdk_aac -f mp4 ./foo.mp4
```

The following won't work:

```
cat client/audio/foo.mp3 | ffmpeg -i pipe:0  -c:a libfdk_aac -f mp4 pipe:1 | cat > foo.mp4
```

I was wondering if there is a way to support converting to `mp4` using this plugin after all. Thanks!

Edit: the failing command gives this error: `[mp4 @ 0x13e47c0] muxer does not support non seekable output`

**Comment by psirenny** [comment]
Yea, if you're streaming (using pipes) then ffmpeg can't infer the audio format because there is no file extension.

You can specify the output explicitly so that this works. e.x.:

```
var ffmpeg = require('gulp-fluent-ffmpeg');

gulp.task('convert', function () {
  return gulp.src('input.mp3')
    .pipe(ffmpeg('mp4'))
    .pipe(gulp.dest('output.mp4'));
  });
```

**Comment by perrin4869** [comment]
hm... just tried it but it didn't work...

```
return gulp.src('client/audio/foo.mp3')
.pipe(ffmpeg('mp4', cmd => cmd
    .audioCodec('libfdk_aac')
))
.pipe(gulp.dest('public/audio/foo.mp4'));
```

The error is the same `ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument`

Ideally, I'd like to do this though:

```
return gulp.src('client/audio/*.mp3')
.pipe(ffmpeg('mp4', cmd => cmd
    .audioCodec('libfdk_aac')
))
.pipe(gulp.dest('public/audio'));
```

**Comment by psirenny** [comment]
Aha, you're right. I should have looked at the error more closely. Another user had the same issue [https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/346](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/346).

His solution was to do something like this:

```
return gulp.src('client/audio/foo.mp3')
  .pipe(ffmpeg('mp4', cmd => cmd
    .audioCodec('libfdk_aac')
    .outputOptions('-movflags frag_keyframe+empty_moov')
  ))
  .pipe(gulp.dest('public/audio/foo.mp4'));
```

Perhaps give that a try?

**Comment by perrin4869** [comment]
yup, that worked like charm :)
thanks!

**Comment by gpoole** [comment]
Hi there, I know it's been a long time since this issue was closed but unfortunately using the `-movflags +faststart` option requires a seekable video stream as well and also isn't compatible with the workaround. I assume using streams also rules out some other options like 2-pass encoding as well. I've locally made some changes to add optional support for sending the output to a temporary file and then replacing `file.contents` with a readable stream of that (plus an optional cleanup step to remove the temp files at the end). Would you be interested in a PR for that feature @psirenny?
