### ISSUE TITLE
Please Bump fluent-ffmpeg to >=2.1.3

### ISSUE THREAD

**Issue by andrew-pyle** [psirenny/gulp-fluent-ffmpeg#10]
## Problem

This package does not interact properly with FFmpeg v7.

## Solution
Bump `fluent-ffmpeg` to `>=2.1.3`.

## Explanation

I encountered an error while using this library in another project: the library wouldn't recognize FFmpeg v7's `lame` for encoding mp3.

```
[15:23:32] Plumber found unhandled error:
 Error: Output format mp3 is not available
```

The issue is apparently in `fluent-ffmpeg`, and the solution is already merged upstream. See this [StackOverflow](https://stackoverflow.com/questions/78451838/fluent-ffmpeg-error-with-mp3-output-format-when-streaming-audio-in-node-js) answer from @totallytavi. 

References:
- https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/1266
- https://github.com/tobspr-games/shapez-community-edition/pull/28
- https://stackoverflow.com/questions/78451838/fluent-ffmpeg-error-with-mp3-output-format-when-streaming-audio-in-node-js

**Comment by psirenny** [comment]
The fluent-ffmpeg version is set to `^2.1.2` which supports all minor and patch updates to that library. In other words, no change should be necessary to this plugin. A new install or updating of your package's lock file should resolve to `fluent-ffmpeg@2.1.3`.

I don't think anything needs to change here so I'm going to close this. But, I'm not opposed to accepting a pull request that also bumps the semver version to `^2.1.3`.
