### ISSUE TITLE
Error: ffmpeg exited with code 1: pipe:0: Invalid data found when processing input

### ISSUE THREAD

**Issue by lucdouwen** [psirenny/gulp-fluent-ffmpeg#5]
Hi, 
Your audio example is running fine, but my video conversions give the error
Error: ffmpeg exited with code 1: pipe:0: Invalid data found when processing input
I must be missing something as the code in https://candyblue.agency/blog/gulp-tasks-video-konvertierung-web/ doesn't work for me neither
I  guess it's related to https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/932 

Thanks for checking
Luc

var gulp = require('gulp');
var ffmpeg = require('gulp-fluent-ffmpeg');
gulp.task('video', function () {
  // transcode mp4 files to webm
  return gulp.src('images/master/K3_DansVanDeFarao_NV_720p.mp4')
    .pipe(ffmpeg('webm', function (cmd) {
      return cmd
        .videoBitrate('1583k')
        .videoCodec('libvpx')
        .audioCodec('libvorbis')
    }))
    .pipe(gulp.dest('images/derivative/webm'));
});

**Comment by psirenny** [comment]
Going to close this issue because it looks like something that should be sorted out in `node-fluent-ffmpeg`. But happy to take another look if there's some action that can be taken here.
